sudo: false
language: node_js
node_js:
  - '6'
  - '8'
env:
  - EGG_VERSION=1
  - EGG_VERSION=2
matrix:
  exclude:
  - node_js: '6'
    env: EGG_VERSION=2
install:
  - npm i npminstall
script:
  - echo "npminstall egg@$EGG_VERSION"
  - eval "npminstall -d egg@$EGG_VERSION"
  - npminstall
  - npm run ci
after_script:
  - npminstall codecov && codecov
